# 部署

language: android
branches:
  only:
    - master
    - develop
    - staging
    - /v\d+\.\d+\.\d+\..*/
android:        # 配置信息
  components:
    # 你可能需要修改下面两项的版本
    - tools
    - build-tools-30.0.3
    - platform-tools
    #    - android-31
    # Android Support Repository
#    - extra-android-m2repository
#    # Support Library
#    - extra-android-support

before_install:
  - chmod +x gradlew
script:
  - ./gradlew assembleRelease