# .travis.yml 文件
language: android
branches:
  only:
    - master
    - develop
    - staging
    - /v\d+\.\d+\.\d+\..*/
android:        # 配置信息
  components:
    # 你可能需要修改下面两项的版本
    - build-tools-29.0.2
    - android-29
    # Android Support Repository
    - extra-android-m2repository
    # Support Library
    - extra-android-support
before_install:
  - chmod +x gradlew

env:
  global:
    - FILE_PATH=app/build/outputs/apk/${Travis_branch}/release/app-prod-release
script: |-
  # 生成 APK
  echo ${TRAVIS_BRANCH}
  if [[ "${TRAVIS_BRANCH}"=~"master" ]]
  then
    ./gradlew assembleProdReleas
  elif [[ "${TRAVIS_BRANCH}"=~"staging" ]]
  then
    ./gradlew assembleStageRelease
  elif [["${TRAVIS_BRANCH}"=~"develop" ]]
  then
    echo "develop"
    ./gradlew assembleDevRelease
  else
    echo "else"
    ./gradlew assembleDevRelease

  fi
# 部署
deploy:
  # 部署到GitHub Release。
  # 除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  provider: releases
  # Github oauth token
  api_key: "${GH_TOKEN}"
  # 部署文件路径；对于Android就部署生成的 apk 文件
  file: "${FILE_PATH}"
  # 避免 Travis CI在部署之前清空生成的APK文件
  skip_cleanup: true
  # 发布时机
  on:
    # tags设置为true表示只有在有tag的情况下才部署
    tags: true
    all_branches: true

