# .travis.yml 文件
language: android
branches:
  only:
    - master
    - develop
    - staging
    - /v\d+\.\d+\.\d+\..*/
android:        # 配置信息
  components:
    # 你可能需要修改下面两项的版本
    - build-tools-30.0.1
    - platform-tools
    #    - android-31
    # Android Support Repository
#    - extra-android-m2repository
#    # Support Library
#    - extra-android-support

before_install:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease
# 部署
deploy:
  # 部署到GitHub Release。
  # 除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  provider: releases
  api_key: "${GH_TOKEN}"
  #provider: s3
  #bucket:
  #access_key_id: "hahaha"
  #secret_access_key: "bbbbb"
  #acl: public_read
  # 部署文件路径；对于Android就部署生成的 apk 文件
  file:
    - app/build/outputs/apk/staging/release/app-staging-release.apk
    - app/build/outputs/apk/demo/release/app-demo-release.apk
    - app/build/outputs/apk/prod/release/app-prod-release.apk
  # 避免 Travis CI在部署之前清空生成的APK文件
  skip_cleanup: true
  # 发布时机
  on:
    # tags设置为true表示只有在有tag的情况下才部署
    tags: true
    all_branches: true